# Generated by Django 3.0.5 on 2020-04-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('from_server', models.CharField(max_length=25)),
                ('to_server', models.CharField(max_length=25)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
    ]
