# Generated by Django 3.0.5 on 2020-04-13 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('copycat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='transfer_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
