# Generated by Django 3.0.5 on 2020-04-15 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('copycat', '0002_transfer_transfer_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.IntegerField()),
                ('time_span', models.CharField(max_length=10)),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
