version: '3.7'
services:
  manager:
    container_name: controller
    build:
      context: ./
      dockerfile: ControllerDockerfile
      args:
        - COPYCAT_IP=192.168.1.188
        - COPYCAT_PORT=4025
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 40025:8000
